//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHangV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int Ma { get; set; }
        public string Ten { get; set; }
        public double DonGia { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
    
        public DanhMuc DanhMuc { get; set; }
    }
}
