//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranVanDung_2019603537
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int MaNV { get; set; }
        public string TenNV { get; set; }
        public decimal HsLuong { get; set; }
    }
}
